GTCV_API_VERSION: str
GTCV_API_VERSION_MAJOR: int
GTCV_API_VERSION_MINOR: int
GTCV_API_VERSION_PATCH: int

class Signal:
    def __init__(self) -> None: ...
    def connect_slot(self, arg0, arg1: capsule) -> None: ...
    def disconnect_slot(self, arg0) -> None: ...
    def emit_signal(self, arg0: capsule) -> None: ...
    def expand_slots(self) -> None: ...
    def free(self) -> None: ...
    def init(self) -> None: ...
